# Generated by Django 2.0.1 on 2018-09-09 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.IntegerField(unique=True, verbose_name='资产ID')),
                ('asset_name', models.CharField(default='unnamed', max_length=128, verbose_name='资产名称')),
                ('asset_type', models.CharField(choices=[('server', '服务器'), ('networkdevice', '网络设备'), ('storagedevice', '存储设备'), ('securitydevice', '安全设备')], default='server', max_length=64, verbose_name='资产类型')),
                ('asset_sn', models.CharField(max_length=128, unique=True, verbose_name='序列号')),
                ('asset_manufacturer', models.CharField(max_length=128, verbose_name='生产商')),
                ('mgmt_ip', models.GenericIPAddressField(verbose_name='管理IP')),
            ],
        ),
        migrations.CreateModel(
            name='Network_device',
            fields=[
                ('assets_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.Assets')),
                ('device_os', models.CharField(max_length=64)),
            ],
            bases=('assets.assets',),
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('assets_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.Assets')),
                ('server_os', models.CharField(max_length=64)),
            ],
            bases=('assets.assets',),
        ),
    ]
